### ISSUE TITLE
Error, founders reward missing for block template!**

### ISSUE THREAD

**Issue by Gondagar** [CommerciumBlockchain/cmmpool#1]
Hello.  Where can i find the actual coin setting for mining? 

https://github.com/CommerciumBlockchain/cmmpool/blob/master/coins/commercium.json
With this config file I get error   **### Error, founders reward missing for block template!**

**Comment by anthony19114** [comment]
Hello, founders reward period is over. You can disable it in the json file. Commercium is having an overhaul, update and coin swap to a new chain. All coins mined will carry over. More info on the Commercium Discord https://discord.gg/QFRUDNm
